// VER PARAMETRO ACTUAL Y EL FORMAL. CUANDO SE PASA INT, FLOAT Y CHAR, ES COMO PASAR UN VALOR.
//LOS DEFINE SE DEFINEN EN ESTE
void mostrarArray(int[], int);
// LA DIFERENCIA ENTRE CONST Y DEFINE ES QUE LA PRIMERA OCUPA LUGAR EN EL MEMORIA.
//LA SEGUNDA ES UNA CONTANTE DEL PREORDENADOR
// UNA CONTANTE TIENE EL MISMO VALOR DESDE QUE INICIA EL PROGRAMA HASTA QUE FINALIZA.
void cargarArray(int[], int);
/** \brief  BUSCA UN VALOR EN EL ARRAY
 *
 * \param [] INT EN EL ARRAY
 * \param INT EN EL TAMAÑO
 * \param INT EN EL VALOR A BUSCAR
 * \return INT EL INDICE DEL VALOR BUSCADO O SI NO LO ENCUENTRA
 *
 */
/** \brief
 *
 * \param
 * \param
 * \return
 *
 */




int buscarValor(int[], int, int);
